### PR TITLE
Fix input flags for esphome 2021.10 in  keypad component

### PR DESCRIPTION
**Pull request by f0rdprefect**

### CODE REVIEW

**Comment by ssieb** [comment]
Thank you.

**Comment by ShadyMCShadesen** [comment]
Well now esphome can compile and upload again but the esp crashes every time i try to press a button o_O

**Comment by ssieb** [comment]
Can you get a decoded stack trace?  I tested the changes I made and it worked perfectly on mine.

**Comment by ShadyMCShadesen** [comment]
> Can you get a decoded stack trace? I tested the changes I made and it worked perfectly on mine.

i found the problem, had a loop that never ended in my display code after a input was made

**Pull request closed without merging**
