### PR TITLE
Update esmart3.cpp

### PR DESCRIPTION
**Pull request by matthias882**
Testet with my ESmart3 charge controller. First i got the "unexpected response code: 0"-message, corrected in line 54, then there were some strange values because of byteswap. corrected in line 126.
Now it works perfect on 60A charge-controller

### CODE REVIEW

**Comment by ssieb** [comment]
Thank you.

**Comment by matthias882** [comment]
I wonder how this worked with the previous code-version (bytesswap in data and the missing first byte in the data-array). I hope there are not two different firmware-versions of esmart-controllers with different communication protocolls on the way. Can you confirm it works now also with your esmart-controller?

**Comment by ssieb** [comment]
It was never tested.  The person I originally wrote the component for couldn't get communication to work on their esmart and I don't have one.  So thank you for testing. :-)

**Comment by matthias882** [comment]
Thats great😂
I can confirm ist works without any problem since six days now and request the data from the controller every 5 seconds.
When I have some hours in future i will try to get some more data out of the esmart.

**Pull request closed without merging**
